version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: deploy/Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - AI_AGENT_URL=http://ai-agent:8000
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    depends_on:
      - ai-agent
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  ai-agent:
    build:
      context: .
      dockerfile: deploy/Dockerfile.agent
    ports:
      - "8000:8000"
    environment:
      - SMART_SERVER_HOST=0.0.0.0
      - SMART_SERVER_PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

networks:
  default:
    name: michal-ai-network